language: bash

services:
  - docker

before_install:
    - docker pull nampdn/node-ipfs:latest
    - docker run --name bara_publisher -d nampdn/node-ipfs > container_id
    - docker ps

script:
    - docker logs bara_publisher
    - docker exec bara_publisher /bin/sh -c "apk add bash jq curl outils-md5"
    - docker exec bara_publisher /bin/bash deploy.sh
