language: bash

cache:
    directories:
        - /home/travis/.ipfs/
services:
  - docker

before_install:
    - docker pull nampdn/node-ipfs:latest
    - docker run --name bara_publisher \
      --env-file <(env | grep -vE "\r|\n" | grep -iE "DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_|AUTH_KEY|ZONE_ID|EMAIL") \
      -v ${PWD}:/project \
      -v /home/travis/.ipfs:/ipfs \
      -e IPFS_PATH=/ipfs \
      -d nampdn/node-ipfs \
      /usr/local/bin/ipfs daemon --init > container_id
    - docker ps

script:
    - docker logs bara_publisher
    - docker exec bara_publisher /bin/sh -c "apk add bash jq curl outils-md5"
    - docker exec bara_publisher /bin/bash /project/deploy.sh
