language: bash

cache:
    directories:
        - $HOME/.ipfs
        
before_cache:
  - sudo rm -rf $HOME/.ipfs
  
services:
  - docker

before_install:
    - docker pull nampdn/node-ipfs:latest
    - docker run -d --name bara_publisher --env-file <(env | grep -vE "\r|\n" | grep -iE "DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_|AUTH_KEY|ZONE_ID|EMAIL") -e ${PWD}:/usr/local/app nampdn/node-ipfs:latest daemon --init

script:
    - docker logs bara_publisher
    - docker exec bara_publisher /bin/sh -c "apk add bash jq curl outils-md5"
    - docker exec bara_publisher /bin/bash -c "pwd && cd /usr/local/app && ls && cat deploy.sh"
# --env-file <(env | grep -vE "\r|\n" | grep -iE "DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_|AUTH_KEY|ZONE_ID|EMAIL") \
